modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="oceanica"
version="${file.jarVersion}"
displayName="Oceanica"
description='''
Oceanica invites you to explore the deep mysteries of the ocean and the eldritch.
'''

[[dependencies.oceanica]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oceanica]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.15.2-1.2-32,)"
    side="BOTH"
